export const FETCH_PLANET_DETAILS = "FETCH_PLANET_DETAILS"
export const SET_PLANET_DETAILS = "SET_PLANET_DETAILS"
export const FETCH_GALAXY_DETAILS = "FETCH_GALAXY_DETAILS"
export const SET_GALAXY_DETAILS = "SET_GALAXY_DETAILS"
export const FETCH_SHIPYARD_DETAILS = "FETCH_SHIPYARD_DETAILS"
export const SET_SHIPYARD_DETAILS = "SET_SHIPYARD_DETAILS"
export const FETCH_TRADES_DETAILS = "FETCH_TRADES_DETAILS"
export const SET_TRADES_DETAILS = "FETCH_TRADES_DETAILS"

export const API = "API"
export const ACCESS_DENIED = "ACCESS_DENIED";
export const API_ERROR = "API_ERROR";
